name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Determine changed services
      id: get_changed_services
      run: |
        if git cat-file -e ${{ github.event.before }} && git cat-file -e ${{ github.sha }}; then
          changed_services=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | awk -F"/" '{print $1}' | sort -u | paste -sd, -)
          echo "Changed services: $changed_services"
          echo "CHANGED_SERVICES=$changed_services" >> $GITHUB_ENV
        else
          echo "Um ou ambos os commits não existem no repositório."
          echo "CHANGED_SERVICES=" >> $GITHUB_ENV
        fi

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push changed services
      run: |
        IFS=',' read -ra SERVICES <<< "$CHANGED_SERVICES"
        IGNORED_DIRECTORIES=(".github")

        for service in "${SERVICES[@]}"; do
            if [[ " ${IGNORED_DIRECTORIES[@]} " =~ " ${service} " ]]; then
                continue
            fi

            echo "Processing $service..."

            response=$(curl -s "https://hub.docker.com/v2/repositories/rafaelsulimann/$service/tags/")

            echo "Resposta do Docker Hub: $response"
            
            if [[ $(echo "$response" | jq '.count') -gt 0 ]]; then
                highest_version=$(echo "$response" | jq -r '[.results[].name | select(test("^v[0-9]+$"))] | sort | .[-1]' | sed 's/v//')
                if [[ ! -z "$highest_version" ]]; then
                    version=$((highest_version + 1))
                else
                    version=1
                fi
                echo "Versão extraída: v$version"
            else
                version=1
            fi

            docker build -t rafaelsulimann/$service:v$version -t rafaelsulimann/$service:latest $service/
            docker push rafaelsulimann/$service:v$version
            docker push rafaelsulimann/$service:latest
        done
